on:
  push:
    branches:    
      - main
      - BatchScanDialog
    paths:
      - '**/RELEASE'
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - BatchScanDialog
    paths:
      - '**/RELEASE'

jobs:
  gh-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pipe-cd/actions-gh-release@v2.3.4
        with:
          release_file: '**/RELEASE'
          token: ${{ secrets.GITHUB_TOKEN }}
