name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,NAPS2.Setup/publish/7.1.2/scanengine-7.1.2-win.exe"
